export const userConstants = {
    SIGN_UP_REQUEST: 'USERS_SIGN_UP_REQUEST',
    SIGN_UP_SUCCESS: 'USERS_SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'USERS_SIGN_UP_FAILURE',

    SIGN_IN_REQUEST: 'USERS_SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'USERS_SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'USERS_SIGN_IN_FAILURE',
    
    SIGN_OUT: 'USERS_LOGOUT',
};
